name: Deploy FE on DockerHub

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Checkout del codice sorgente
    - uses: actions/checkout@v3

    # Imposta Node.js (necessario per Flutter Web Build)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    # Installa Flutter
    - name: Install Flutter
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.13.5-stable.tar.xz
        tar -xf flutter_linux_3.13.5-stable.tar.xz
        export PATH="$PATH:$PWD/flutter/bin"
        flutter doctor

    # Build dell'applicazione Flutter per il web
    - name: Build Flutter Web
      run: |
        export PATH="$PATH:$PWD/flutter/bin"
        flutter build web --release

    # Login a Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build dell'immagine Docker
    - name: Build Docker image
      run: docker build -t giuliapugliese/agenda-frontend:latest .

    # Push dell'immagine Docker su Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push giuliapugliese/agenda-frontend:latest
